CREATE TABLE PETUGASPARKIR ( 
	idPetugas MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
    namaPetugas VARCHAR(15) NOT NULL,
	emailPetugas VARCHAR(50) NOT NULL,
    noHpPetugas VARCHAR(15) NOT NULL,
    usernamePetugas VARCHAR(15) NOT NULL,
    passwordPetugas VARCHAR(15) NOT NULL
);

CREATE TABLE PENGATURANPARKIR(
	idPengaturan MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
    tarifParkirMobilPerJam MEDIUMINT NOT NULL,
    tarifParkirMotorPerJam MEDIUMINT NOT NULL,
    tarifParkirMobilPerHari MEDIUMINT NOT NULL,
    tarifParkirMotorPerHari MEDIUMINT,
    kuotaParkirMotor MEDIUMINT NOT NULL,
    kuotaParkirMobil MEDIUMINT NOT NULL,
    waktuAtur DATETIME NOT NULL,
    idPetugas MEDIUMINT NOT NULL, 
    CONSTRAINT FOREIGN KEY (idPetugas) REFERENCES PETUGASPARKIR(idPetugas)
);

CREATE TABLE PARKIRPERJAM(
	idParkirPerJam MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
    waktuMasuk DATETIME NOT NULL,
    waktuKeluar DATETIME
);

CREATE TABLE PARKIRINAP(
	idParkirInap MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
    tanggalMasuk DATE NOT NULL,
    tanggalKeluar DATE 
);

CREATE TABLE PARKIR (
    idParkir MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
    idPengaturan MEDIUMINT NOT NULL,
    nomorKendaraan VARCHAR(12) NOT NULL,
    jenisKendaraan VARCHAR(5) NOT NULL,
    tipeParkir VARCHAR(7) NOT NULL,
    statusParkir VARCHAR(7) NOT NULL,
    idParkirPerJam MEDIUMINT,
    idParkirInap MEDIUMINT,
    CONSTRAINT FOREIGN KEY (idPengaturan) REFERENCES PENGATURANPARKIR(idPengaturan),
    CONSTRAINT FOREIGN KEY (idParkirPerJam) REFERENCES PARKIRPERJAM(idParkirPerJam),
    CONSTRAINT FOREIGN KEY (idParkirInap) REFERENCES PARKIRINAP(idParkirInap)
);

CREATE TABLE PEMBAYARAN (
	idPembayaran MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
    idParkir MEDIUMINT NOT NULL,
    waktuPembayaran DATETIME NOT NULL,
    totalBayar MEDIUMINT NOT NULL,
    idPetugas MEDIUMINT,
    CONSTRAINT FOREIGN KEY (idParkir) REFERENCES PARKIR(idParkir),
    CONSTRAINT FOREIGN KEY (idPetugas) REFERENCES PETUGASPARKIR(idPetugas)
);
