package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pravi
 */

/**
 * Import.
 */
import Model.Parkir;
import Model.ParkirPerJam;
import Model.ParkirInap;
import Controller.ParkirController;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.time.LocalDate;
import Model.Pembayaran;
import Controller.PembayaranController;
import javax.swing.JOptionPane;

/**
 * Main Keluar Parkir window of the application.
 */
public class KeluarParkir extends javax.swing.JFrame {

    /**
     * Creates new form keluar parkir
     */
    private final ParkirController parkirC = new ParkirController(); // Controller variable for parking
    private final PembayaranController pembayaranC = new PembayaranController(); // Controller variable for payment
    
    public KeluarParkir() {
        initComponents();
        setLocationRelativeTo(null);
        Komponen.addPlaceholderStyleJ(platNomorTextField);
        Komponen.removePlaceholderStyleJ(platNomorTextField);
        Komponen.setOnlyIntegerJ(nominalTextField);
        Komponen.setOnlyAlphaNumericJ(platNomorTextField);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keluarParkirMainLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        typeOfVehicleLabel = new javax.swing.JLabel();
        vehicleRegistrationNumberLabel = new javax.swing.JLabel();
        paymentNominalLabel = new javax.swing.JLabel();
        arrivalTimeLabel = new javax.swing.JLabel();
        exitTimeLabel = new javax.swing.JLabel();
        changeAmountLabel = new javax.swing.JLabel();
        platNomorTextField = new javax.swing.JTextField();
        totalCostLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nominalTextField = new javax.swing.JTextField();
        changeAmountPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        costPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        arrivalTimePanel = new javax.swing.JPanel();
        arrivalTimeValueLabel = new javax.swing.JLabel();
        exitTimePanel = new javax.swing.JPanel();
        exitTimeValueLabell = new javax.swing.JLabel();
        typeOfVehicleValueLabel = new javax.swing.JLabel();
        searchButton = new java.awt.Button();
        saveButton = new java.awt.Button();
        changeAmountCheckButton = new java.awt.Button();
        leftPanel = new javax.swing.JPanel();
        radeamLeftText = new javax.swing.JLabel();
        dashboardNavButton = new java.awt.Button();
        masukParkirNavButton = new java.awt.Button();
        keluarParkirNavButton = new java.awt.Button();
        pengaturanParkirNavButton = new java.awt.Button();
        laporanParkirNavButton = new java.awt.Button();
        raedamLeftLogo = new javax.swing.JLabel();
        parkingDataSubtitlePanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        raedamRightLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pembayaran");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        keluarParkirMainLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        keluarParkirMainLabel.setForeground(new java.awt.Color(102, 204, 255));
        keluarParkirMainLabel.setText("KELUAR PARKIR");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        typeOfVehicleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        typeOfVehicleLabel.setText("Jenis Kendaraan ");

        vehicleRegistrationNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vehicleRegistrationNumberLabel.setText("Plat Nomor ");

        paymentNominalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paymentNominalLabel.setText("Nominal Pembayaran ");

        arrivalTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrivalTimeLabel.setText("Waktu Masuk");

        exitTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitTimeLabel.setText("Waktu Keluar");

        changeAmountLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        changeAmountLabel.setText("Total Kembalian");

        platNomorTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        platNomorTextField.setText("Masukkan Nomor Plat");
        platNomorTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                platNomorTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                platNomorTextFieldFocusLost(evt);
            }
        });

        totalCostLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalCostLabel.setText("Total Biaya  ");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        nominalTextField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nominalTextField.setText("Masukkan Nominal Bayar");
        nominalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalTextFieldActionPerformed(evt);
            }
        });

        changeAmountPanel.setBackground(new java.awt.Color(255, 255, 255));
        changeAmountPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel11.setText("-");

        javax.swing.GroupLayout changeAmountPanelLayout = new javax.swing.GroupLayout(changeAmountPanel);
        changeAmountPanel.setLayout(changeAmountPanelLayout);
        changeAmountPanelLayout.setHorizontalGroup(
            changeAmountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeAmountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        changeAmountPanelLayout.setVerticalGroup(
            changeAmountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeAmountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        costPanel.setBackground(new java.awt.Color(255, 255, 255));
        costPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        costPanel.setPreferredSize(new java.awt.Dimension(234, 47));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Rp. 0");

        javax.swing.GroupLayout costPanelLayout = new javax.swing.GroupLayout(costPanel);
        costPanel.setLayout(costPanelLayout);
        costPanelLayout.setHorizontalGroup(
            costPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        costPanelLayout.setVerticalGroup(
            costPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(changeAmountPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nominalTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(costPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(nominalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(changeAmountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nominalTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nominalTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nominalTextFieldFocusLost(evt);
            }
        });

        arrivalTimePanel.setBackground(new java.awt.Color(255, 255, 255));
        arrivalTimePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        arrivalTimeValueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arrivalTimeValueLabel.setText("-");

        javax.swing.GroupLayout arrivalTimePanelLayout = new javax.swing.GroupLayout(arrivalTimePanel);
        arrivalTimePanel.setLayout(arrivalTimePanelLayout);
        arrivalTimePanelLayout.setHorizontalGroup(
            arrivalTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrivalTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arrivalTimeValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        arrivalTimePanelLayout.setVerticalGroup(
            arrivalTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(arrivalTimeValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        exitTimePanel.setBackground(new java.awt.Color(255, 255, 255));
        exitTimePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        exitTimeValueLabell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitTimeValueLabell.setText("-");

        javax.swing.GroupLayout exitTimePanelLayout = new javax.swing.GroupLayout(exitTimePanel);
        exitTimePanel.setLayout(exitTimePanelLayout);
        exitTimePanelLayout.setHorizontalGroup(
            exitTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTimeValueLabell, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitTimePanelLayout.setVerticalGroup(
            exitTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTimeValueLabell, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        typeOfVehicleValueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        typeOfVehicleValueLabel.setText("-");

        searchButton.setBackground(new java.awt.Color(102, 204, 255));
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setLabel("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        saveButton.setActionCommand("tombolSelesai");
        saveButton.setBackground(new java.awt.Color(102, 204, 255));
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setLabel("Selesai");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        changeAmountCheckButton.setBackground(new java.awt.Color(102, 204, 255));
        changeAmountCheckButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeAmountCheckButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        changeAmountCheckButton.setForeground(new java.awt.Color(255, 255, 255));
        changeAmountCheckButton.setLabel("Cek Kembalian");
        changeAmountCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeAmountCheckButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeOfVehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleRegistrationNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paymentNominalLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(changeAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(typeOfVehicleValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(platNomorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(changeAmountCheckButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(154, 154, 154)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(arrivalTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vehicleRegistrationNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(platNomorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeOfVehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeOfVehicleValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arrivalTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(exitTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(paymentNominalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(changeAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(exitTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(changeAmountCheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        leftPanel.setBackground(new java.awt.Color(102, 204, 255));

        radeamLeftText.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        radeamLeftText.setForeground(new java.awt.Color(255, 255, 255));
        radeamLeftText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radeamLeftText.setText("Raedam");

        dashboardNavButton.setActionCommand("beranda");
        dashboardNavButton.setBackground(new java.awt.Color(102, 204, 255));
        dashboardNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        dashboardNavButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardNavButton.setLabel("Beranda");
        dashboardNavButton.setPreferredSize(new java.awt.Dimension(116, 41));
        dashboardNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardNavButtonActionPerformed(evt);
            }
        });

        masukParkirNavButton.setActionCommand("masukParkir");
        masukParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        masukParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masukParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        masukParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        masukParkirNavButton.setLabel("Masuk Parkir");
        masukParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukParkirNavButtonActionPerformed(evt);
            }
        });

        keluarParkirNavButton.setActionCommand("keluarParkir");
        keluarParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        keluarParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluarParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        keluarParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        keluarParkirNavButton.setLabel("Keluar Parkir");
        keluarParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarParkirNavButtonActionPerformed(evt);
            }
        });

        pengaturanParkirNavButton.setActionCommand("pengaturanParkir");
        pengaturanParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        pengaturanParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengaturanParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        pengaturanParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        pengaturanParkirNavButton.setLabel("Pengaturan Parkir");
        pengaturanParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengaturanParkirNavButtonActionPerformed(evt);
            }
        });

        laporanParkirNavButton.setActionCommand("laporanParkir");
        laporanParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        laporanParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        laporanParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        laporanParkirNavButton.setLabel("Laporan Parkir");
        laporanParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanParkirNavButtonActionPerformed(evt);
            }
        });

        raedamLeftLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/WhatsApp_Image_2023-10-17_at_12.55.56-removebg-preview.png"))); // NOI18N
        raedamLeftLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raedamLeftLogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radeamLeftText, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dashboardNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(masukParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(keluarParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pengaturanParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laporanParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(raedamLeftLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(raedamLeftLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radeamLeftText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(dashboardNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(masukParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(keluarParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pengaturanParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(laporanParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parkingDataSubtitlePanel.setBackground(new java.awt.Color(102, 204, 255));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Data Parkir");
        jLabel20.setToolTipText("");

        javax.swing.GroupLayout parkingDataSubtitlePanelLayout = new javax.swing.GroupLayout(parkingDataSubtitlePanel);
        parkingDataSubtitlePanel.setLayout(parkingDataSubtitlePanelLayout);
        parkingDataSubtitlePanelLayout.setHorizontalGroup(
            parkingDataSubtitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkingDataSubtitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        parkingDataSubtitlePanelLayout.setVerticalGroup(
            parkingDataSubtitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkingDataSubtitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        raedamRightLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Untitled-removebg-preview (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parkingDataSubtitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(keluarParkirMainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(raedamRightLogo))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(raedamRightLogo)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(keluarParkirMainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parkingDataSubtitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Ensures that the window remains focused.
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * Handles the action when the "Beranda" button is clicked.
     */
    private void dashboardNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardNavButtonActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_dashboardNavButtonActionPerformed

    /**
     * Handles the action when the "Masuk Parkir" button is clicked.
     */
    private void masukParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new MasukParkir().setVisible(true);
        dispose();
    }//GEN-LAST:event_masukParkirNavButtonActionPerformed

    /**
     * Handles the action when the "Keluar Parkir" button is clicked.
     */
    private void keluarParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new KeluarParkir().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarParkirNavButtonActionPerformed

    /**
     * Handles the action when the "Pengaturan Parkir" button is clicked.
     */
    private void pengaturanParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengaturanParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new PengaturanParkirView().setVisible(true);
        dispose();
    }//GEN-LAST:event_pengaturanParkirNavButtonActionPerformed

    /**
     * Handles the action when the "Laporan Parkir" button is clicked.
     */
    private void laporanParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new TampilData().setVisible(true);
        dispose();
    }//GEN-LAST:event_laporanParkirNavButtonActionPerformed

    /**
     * Defines a method called when focus is lost from the plat nomor field, if the column is blank, add a placeholder style and set the text to "Enter License Plate Number.
     */
    private void platNomorTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_platNomorTextFieldFocusLost
        if (platNomorTextField.getText().length() == 0){
            Komponen.addPlaceholderStyleJ(platNomorTextField);
            platNomorTextField.setText("Masukkan Nomor Plat");
        } 
    }//GEN-LAST:event_platNomorTextFieldFocusLost

    /** 
     * This method handles gaining focus for the license plate number field,
     * If the text is "Masukkan Nomor Plat" (Enter License Plate), it removes the text, 
     * requests focus, and removes the placeholder style.
     */
    private void platNomorTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_platNomorTextFieldFocusGained
        if (platNomorTextField.getText().equals("Masukkan Nomor Plat")){
            platNomorTextField.setText("");
            platNomorTextField.requestFocus();
            Komponen.removePlaceholderStyleJ(platNomorTextField);
        }
    }//GEN-LAST:event_platNomorTextFieldFocusGained
 
    /**
     * This method, when the "Simpan" (Save) button is clicked, validates the input, calculates the total payment,
     * updates the parking status, adds payment notes, opens a new dashboard window, and closes the current window.
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            String platNomor = platNomorTextField.getText().replace(" ", "");
            int nominalBayar = (nominalTextField.getText().equalsIgnoreCase("Masukkan Nominal Bayar")) ? 0 : Integer.parseInt(nominalTextField.getText());
            System.out.println(nominalBayar);
            Parkir parkir = parkirC.searchByPlateNum(platNomor);
            if (parkir != null) {
                int totalBayar = pembayaranC.hitungTotalBayar(parkir);
                
                if (nominalBayar >= totalBayar) {
                    if (parkir.getTipeParkir().equalsIgnoreCase("PERJAM")){
                        ((ParkirPerJam) parkir).keluarParkir();
                    } else {
                        ((ParkirInap) parkir).keluarParkir();
                    }
                    parkirC.updateParkir(parkir);
                    Pembayaran pembayaran = new Pembayaran(totalBayar, LocalDateTime.now(), parkir, Session.sesi.petugas);
                    pembayaranC.insertPembayaran(pembayaran);
                    pembayaranC.addPembayaran(pembayaran);
                    new Dashboard().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(KeluarParkir.this, "Nominal Pembayaran tidak sesuai. Mohon refresh atau masukkan nominal yang sesuai");
                } 
            } else {
                JOptionPane.showMessageDialog(KeluarParkir.this, "Data kendaraan tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(KeluarParkir.this, "Mohon masukkan/cari data kendaraan");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * This method is triggered when the "Cari" (Search) button is clicked,
     * It searches for a vehicle based on the license plate number, displays relevant information,
     * and calculates the total payment.
     */  
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String platNomor = platNomorTextField.getText();
        Parkir parkir = parkirC.searchByPlateNum(platNomor);
        if (parkir != null && parkir.getStatusParkir().equals("PARKIR")){
            typeOfVehicleValueLabel.setText(parkir.getJenisKendaraan());
            if (parkir.getTipeParkir().equalsIgnoreCase("PERJAM")) {
                arrivalTimeValueLabel.setText(((ParkirPerJam) parkir).getWaktuMasuk().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")));
                exitTimeValueLabell.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")));
                ((ParkirPerJam) parkir).setWaktuKeluar(LocalDateTime.now());
            } else {
                arrivalTimeValueLabel.setText(((ParkirInap) parkir).getTanggalMasuk().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
                exitTimeValueLabell.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
                ((ParkirInap) parkir).setTanggalKeluar(LocalDate.now());
            }
        
            jLabel17.setText(String.valueOf(pembayaranC.hitungTotalBayar(parkir)));
        } else {
            JOptionPane.showMessageDialog(KeluarParkir.this, "Data Kendaraan Tidak Ditemukan");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * This method is triggered when the "Periksa Jumlah Kembalian" button is clicked,
     * It calculates and displays the change amount based on the entered payment amount.
     */  
    private void changeAmountCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeAmountCheckButtonActionPerformed
        try {
            String platNomor = platNomorTextField.getText();
            int nominalBayar = Integer.parseInt(nominalTextField.getText());
            
            Parkir parkir = parkirC.searchByPlateNum(platNomor);
            nominalBayar = Integer.parseInt(nominalTextField.getText()); 
            int totalKembalian = nominalBayar - pembayaranC.hitungTotalBayar(parkir);
        
            if (totalKembalian < 0) {
                jLabel11.setText(String.valueOf("Nominal Tidak Valid"));
            } else {
                jLabel11.setText(String.valueOf(totalKembalian));
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(KeluarParkir.this, "Mohon masukkan data kendaraan");
        }
        
    }//GEN-LAST:event_changeAmountCheckButtonActionPerformed

    /**
     * Opens the dashboard window and closes the current window.
     */
    private void raedamLeftLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raedamLeftLogoMouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_raedamLeftLogoMouseClicked

    private void nominalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominalTextFieldActionPerformed
    
    /**
     * This method handles losing focus for the payment amount field,
     * If the field is empty, it adds the placeholder style and sets the text to "Masukkan Nominal Bayar" (Enter Payment Amount).
     */
    private void nominalTextFieldFocusLost(java.awt.event.FocusEvent evt) {                                             
        if (nominalTextField.getText().length() == 0){
            Komponen.addPlaceholderStyleJ(nominalTextField);
            nominalTextField.setText("Masukkan Nominal Bayar");
        } 
    }                                            

    /**
     * This method handles gaining focus for the payment amount field,
     * If the text is "Masukkan Nominal Bayar" (Enter Payment Amount), it removes the text, 
     * requests focus, and removes the placeholder style.
     */
    private void nominalTextFieldFocusGained(java.awt.event.FocusEvent evt) {                                               
        if (nominalTextField.getText().equals("Masukkan Nominal Bayar")){
            nominalTextField.setText(null);
            nominalTextField.requestFocus();
            Komponen.removePlaceholderStyleJ(nominalTextField);
        } 
    }  
    
    /**
     * Main method to run the application.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeluarParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeluarParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeluarParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeluarParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeluarParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrivalTimeLabel;
    private javax.swing.JPanel arrivalTimePanel;
    private javax.swing.JLabel arrivalTimeValueLabel;
    private java.awt.Button changeAmountCheckButton;
    private javax.swing.JLabel changeAmountLabel;
    private javax.swing.JPanel changeAmountPanel;
    private javax.swing.JPanel costPanel;
    private java.awt.Button dashboardNavButton;
    private javax.swing.JLabel exitTimeLabel;
    private javax.swing.JPanel exitTimePanel;
    private javax.swing.JLabel exitTimeValueLabell;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel keluarParkirMainLabel;
    private java.awt.Button keluarParkirNavButton;
    private java.awt.Button laporanParkirNavButton;
    private javax.swing.JPanel leftPanel;
    private java.awt.Button masukParkirNavButton;
    private javax.swing.JTextField nominalTextField;
    private javax.swing.JPanel parkingDataSubtitlePanel;
    private javax.swing.JLabel paymentNominalLabel;
    private java.awt.Button pengaturanParkirNavButton;
    private javax.swing.JTextField platNomorTextField;
    private javax.swing.JLabel radeamLeftText;
    private javax.swing.JLabel raedamLeftLogo;
    private javax.swing.JLabel raedamRightLogo;
    private java.awt.Button saveButton;
    private java.awt.Button searchButton;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JLabel typeOfVehicleLabel;
    private javax.swing.JLabel typeOfVehicleValueLabel;
    private javax.swing.JLabel vehicleRegistrationNumberLabel;
    // End of variables declaration//GEN-END:variables
}
