package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */

/**
 * Import.
 */
import Controller.ParkirController;
import Controller.PengaturanParkirController;
import Model.Parkir;
import Model.ParkirInap;
import Model.ParkirPerJam;
import javax.swing.JOptionPane;

/**
 * Main Masuk Parkir window of the application.
 */
public class MasukParkir extends javax.swing.JFrame {
    
    private final ParkirController parkirC = new ParkirController(); // Controller variable for parking
    private final PengaturanParkirController pengaturanC = new PengaturanParkirController(); // Controller variable for parking settings
    private String jenisKendaraan; // Variable to store vehicle type
    private String tipeParkir; // Variable to store vehicle type
    
    /**
     * Creates new form MasukParkir
     */
    public MasukParkir() {
        initComponents();
        setLocationRelativeTo(null);
        Komponen.addPlaceholderStyleJ(nomorKendaraanTextField);
        Komponen.removePlaceholderStyleJ(nomorKendaraanTextField);
        Komponen.setOnlyAlphaNumericJ(nomorKendaraanTextField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeOfVehicleButtonGroup = new javax.swing.ButtonGroup();
        typeOfParkirButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        nomorKendaraanTextField = new javax.swing.JTextField();
        motorRadioButton = new javax.swing.JRadioButton();
        mobilRadioButton = new javax.swing.JRadioButton();
        simpanButton = new java.awt.Button();
        parkingDataLabel = new java.awt.Label();
        vehicleRegistrationNumberLabel = new java.awt.Label();
        typeOfVehicleLabel = new java.awt.Label();
        typeOfParkirLabel = new java.awt.Label();
        perJamRadioButton = new javax.swing.JRadioButton();
        perHariRadioButton = new javax.swing.JRadioButton();
        masukParkirTitleLabel = new javax.swing.JLabel();
        subtitlePanel = new javax.swing.JPanel();
        parkingDataSubtitleLabel = new javax.swing.JLabel();
        rightRaedamLogo = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        raedamLeftLogo = new javax.swing.JLabel();
        raedamLeftLabel = new javax.swing.JLabel();
        dashboardNavButton = new java.awt.Button();
        masukParkirNavButton = new java.awt.Button();
        keluarParkirNavButton = new java.awt.Button();
        pengaturanParkirNavButton = new java.awt.Button();
        laporanParkirNavButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        nomorKendaraanTextField.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        nomorKendaraanTextField.setForeground(new java.awt.Color(204, 204, 204));
        nomorKendaraanTextField.setText("Masukkan Plat");
        nomorKendaraanTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nomorKendaraanTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomorKendaraanTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomorKendaraanTextFieldFocusLost(evt);
            }
        });

        typeOfVehicleButtonGroup.add(motorRadioButton);
        motorRadioButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        motorRadioButton.setText("Motor");
        motorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorRadioButtonActionPerformed(evt);
            }
        });

        typeOfVehicleButtonGroup.add(mobilRadioButton);
        mobilRadioButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        mobilRadioButton.setText("Mobil");
        mobilRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilRadioButtonActionPerformed(evt);
            }
        });

        simpanButton.setActionCommand("simpanButton");
        simpanButton.setBackground(new java.awt.Color(102, 204, 255));
        simpanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        simpanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanButton.setLabel("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        parkingDataLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        parkingDataLabel.setText("Data Parkir Kendaraan");

        vehicleRegistrationNumberLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        vehicleRegistrationNumberLabel.setText("Plat Nomor Kendaraan");

        typeOfVehicleLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        typeOfVehicleLabel.setText("Jenis Kendaraan");

        typeOfParkirLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        typeOfParkirLabel.setText("Jenis Parkir");

        typeOfParkirButtonGroup.add(perJamRadioButton);
        perJamRadioButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        perJamRadioButton.setText("PerJam");
        perJamRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perJamRadioButtonActionPerformed(evt);
            }
        });

        typeOfParkirButtonGroup.add(perHariRadioButton);
        perHariRadioButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        perHariRadioButton.setText("PerHari");
        perHariRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perHariRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parkingDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicleRegistrationNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(typeOfVehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(typeOfParkirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomorKendaraanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(perJamRadioButton)
                                            .addComponent(motorRadioButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(perHariRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(mobilRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(parkingDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nomorKendaraanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(vehicleRegistrationNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(motorRadioButton)
                        .addComponent(mobilRadioButton))
                    .addComponent(typeOfVehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeOfParkirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(perJamRadioButton)
                        .addComponent(perHariRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        masukParkirTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        masukParkirTitleLabel.setForeground(new java.awt.Color(102, 204, 255));
        masukParkirTitleLabel.setText("MASUK PARKIR");

        subtitlePanel.setBackground(new java.awt.Color(102, 204, 255));

        parkingDataSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        parkingDataSubtitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        parkingDataSubtitleLabel.setText("Data Kendaraan Parkir");
        parkingDataSubtitleLabel.setToolTipText("");

        javax.swing.GroupLayout subtitlePanelLayout = new javax.swing.GroupLayout(subtitlePanel);
        subtitlePanel.setLayout(subtitlePanelLayout);
        subtitlePanelLayout.setHorizontalGroup(
            subtitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parkingDataSubtitleLabel)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        subtitlePanelLayout.setVerticalGroup(
            subtitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parkingDataSubtitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightRaedamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Untitled-removebg-preview (1).png"))); // NOI18N

        leftPanel.setBackground(new java.awt.Color(102, 204, 255));

        raedamLeftLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/WhatsApp_Image_2023-10-17_at_12.55.56-removebg-preview.png"))); // NOI18N
        raedamLeftLogo.setText("jLabel4");
        raedamLeftLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raedamLeftLogoMouseClicked(evt);
            }
        });

        raedamLeftLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        raedamLeftLabel.setForeground(new java.awt.Color(255, 255, 255));
        raedamLeftLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        raedamLeftLabel.setText("Raedam");

        dashboardNavButton.setActionCommand("beranda");
        dashboardNavButton.setBackground(new java.awt.Color(102, 204, 255));
        dashboardNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        dashboardNavButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardNavButton.setLabel("Beranda");
        dashboardNavButton.setPreferredSize(new java.awt.Dimension(116, 41));
        dashboardNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardNavButtonActionPerformed(evt);
            }
        });

        masukParkirNavButton.setActionCommand("masukParkir");
        masukParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        masukParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masukParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        masukParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        masukParkirNavButton.setLabel("Masuk Parkir");
        masukParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukParkirNavButtonActionPerformed(evt);
            }
        });

        keluarParkirNavButton.setActionCommand("keluarParkir");
        keluarParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        keluarParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluarParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        keluarParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        keluarParkirNavButton.setLabel("Keluar Parkir");
        keluarParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarParkirNavButtonActionPerformed(evt);
            }
        });

        pengaturanParkirNavButton.setActionCommand("pengaturanParkir");
        pengaturanParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        pengaturanParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengaturanParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        pengaturanParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        pengaturanParkirNavButton.setLabel("Pengaturan Parkir");
        pengaturanParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengaturanParkirNavButtonActionPerformed(evt);
            }
        });

        laporanParkirNavButton.setActionCommand("laporanParkir");
        laporanParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        laporanParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        laporanParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        laporanParkirNavButton.setLabel("Laporan Parkir");
        laporanParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanParkirNavButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(raedamLeftLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(raedamLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(masukParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keluarParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pengaturanParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laporanParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(raedamLeftLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(raedamLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(dashboardNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(masukParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(keluarParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pengaturanParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(laporanParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(subtitlePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(masukParkirTitleLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(654, 654, 654)
                        .addComponent(rightRaedamLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rightRaedamLogo)
                .addGap(35, 35, 35)
                .addComponent(masukParkirTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(subtitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is called when the user performs an action on the car radio button (mobilRadioButton).
     */
    private void mobilRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilRadioButtonActionPerformed
        jenisKendaraan = "MOBIL";
    }//GEN-LAST:event_mobilRadioButtonActionPerformed

    /**
     * This method is called when the user performs an action on the motorcycle radio button (motorRadioButton).
     */
    private void motorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorRadioButtonActionPerformed
        jenisKendaraan = "MOTOR";
    }//GEN-LAST:event_motorRadioButtonActionPerformed

    /**
     * This method is called when the nomorKendaraanTextField gains focus.
     */
    private void nomorKendaraanTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomorKendaraanTextFieldFocusGained
        if (nomorKendaraanTextField.getText().equals("Masukkan Plat")){
            nomorKendaraanTextField.setText(null);
            nomorKendaraanTextField.requestFocus();
            Komponen.removePlaceholderStyleJ(nomorKendaraanTextField);
        }
    }//GEN-LAST:event_nomorKendaraanTextFieldFocusGained

    /**
     * This method is called when nomorKendaraanTextField loses focus.
     */
    private void nomorKendaraanTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomorKendaraanTextFieldFocusLost
        if (nomorKendaraanTextField.getText().length() == 0){
            Komponen.addPlaceholderStyleJ(nomorKendaraanTextField);
            nomorKendaraanTextField.setText("Masukkan Plat");
        } 
    }//GEN-LAST:event_nomorKendaraanTextFieldFocusLost

    /**
     * Ensures that the window remains focused.
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * Handles the action when the "Beranda" button is clicked.
     */
    private void dashboardNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardNavButtonActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_dashboardNavButtonActionPerformed

    /**
     * Handles the action when the "Masuk Parkir" button is clicked.
     */
    private void masukParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new MasukParkir().setVisible(true);
        dispose();
    }//GEN-LAST:event_masukParkirNavButtonActionPerformed

    /**
     * Handles the action when the "Keluar Parkir" button is clicked.
     */
    private void keluarParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new KeluarParkir().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarParkirNavButtonActionPerformed

    /**
     * Handles the action when the "Pengaturan Parkir" button is clicked.
     */
    private void pengaturanParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengaturanParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new PengaturanParkirView().setVisible(true);
        dispose();
    }//GEN-LAST:event_pengaturanParkirNavButtonActionPerformed

    /**
     * Handles the action when the "Laporan Parkir" button is clicked.
     */
    private void laporanParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new TampilData().setVisible(true);
        dispose();
    }//GEN-LAST:event_laporanParkirNavButtonActionPerformed

    /**
     * The simpanButtonActionPerformed method is triggered when the user clicks the "Simpan" button.
     * Retrieves the vehicle plate number from the nomorKendaraanTextField.
     * Checks if jenisKendaraan, nomorKendaraan, and tipeParkir have been selected or filled.
     * Verifies the existence of parking settings (pengaturanC.getPengaturanParkir()).
     * Checks if there is available parking space for the selected vehicle type.
     * @param evt 
     */
    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        String nomorKendaraan = nomorKendaraanTextField.getText();
        if (!nomorKendaraan.isEmpty() && !jenisKendaraan.isEmpty() && !tipeParkir.isEmpty()){
            if (pengaturanC.getPengaturanParkir()!=null) {
                if (parkirC.searchByPlateNum(nomorKendaraan) == null) {
                    if (parkirC.isParkirKosong(jenisKendaraan)) {
                    Parkir parkir = parkirC.createObjekMasukParkir(nomorKendaraan, jenisKendaraan, tipeParkir);
                    if (parkir instanceof ParkirPerJam){
                        ((ParkirPerJam) parkir).masukParkir(tipeParkir);
                        parkirC.insertParkir(parkir);
                    } else {
                        ((ParkirInap) parkir).masukParkir(tipeParkir);
                        parkirC.insertParkir(parkir);
                    }
                    JOptionPane.showMessageDialog(this, "Data parkir berhasil ditambahkan");
                    new Dashboard().setVisible(true);
                    dispose();
                    } else {
                        JOptionPane.showMessageDialog(MasukParkir.this, "Parkir Penuh!!");
                    }
                } else {
                    JOptionPane.showMessageDialog(MasukParkir.this, "Plat nomor telah terdaftar sebagai kendaraan yang sedang parkir");
                }
            } else {
                JOptionPane.showMessageDialog(MasukParkir.this, "Mohon Isi Pengaturan Parkir Terlebih Dahulu");
            }
            
        } else {
            JOptionPane.showMessageDialog(MasukParkir.this, "Mohon isi semua data yang diperlukan!");
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    /**
     * This method is called when the user selects the "Per Jam" radio button (perJamRadioButton).
     */
    private void perJamRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perJamRadioButtonActionPerformed
        tipeParkir = "PERJAM";
    }//GEN-LAST:event_perJamRadioButtonActionPerformed
    
    /**
     * This method is called when the user selects the "Per Hari" radio button (perHariRadioButton).
     */
    private void perHariRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perHariRadioButtonActionPerformed
        tipeParkir = "INAP";
    }//GEN-LAST:event_perHariRadioButtonActionPerformed

    /**
     * Opens the dashboard window and closes the current window.
     */
    private void raedamLeftLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raedamLeftLogoMouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_raedamLeftLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasukParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasukParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasukParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasukParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasukParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button dashboardNavButton;
    private java.awt.Button keluarParkirNavButton;
    private java.awt.Button laporanParkirNavButton;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private java.awt.Button masukParkirNavButton;
    private javax.swing.JLabel masukParkirTitleLabel;
    private javax.swing.JRadioButton mobilRadioButton;
    private javax.swing.JRadioButton motorRadioButton;
    private javax.swing.JTextField nomorKendaraanTextField;
    private java.awt.Label parkingDataLabel;
    private javax.swing.JLabel parkingDataSubtitleLabel;
    private java.awt.Button pengaturanParkirNavButton;
    private javax.swing.JRadioButton perHariRadioButton;
    private javax.swing.JRadioButton perJamRadioButton;
    private javax.swing.JLabel raedamLeftLabel;
    private javax.swing.JLabel raedamLeftLogo;
    private javax.swing.JLabel rightRaedamLogo;
    private java.awt.Button simpanButton;
    private javax.swing.JPanel subtitlePanel;
    private javax.swing.ButtonGroup typeOfParkirButtonGroup;
    private java.awt.Label typeOfParkirLabel;
    private javax.swing.ButtonGroup typeOfVehicleButtonGroup;
    private java.awt.Label typeOfVehicleLabel;
    private java.awt.Label vehicleRegistrationNumberLabel;
    // End of variables declaration//GEN-END:variables
}
