package View;

import Controller.PetugasController;

/**
 *
 * @author achmadfahriza
 */

/**
 * Import.
 */
import javax.swing.JOptionPane;

/**
 * Main registration window of the application.
 */
public class Registrasi extends javax.swing.JFrame {

    private final PetugasController petugasC = new PetugasController();// Controller variable for officer
    private boolean showPassword = false; // Variable to store show password settings
    private boolean showConfirmationPassword = false; // Variable to store show password confirmation settings
    
    /**
     * Creates new form registrasi.
     */
    public Registrasi() {
        initComponents();
        setLocationRelativeTo(null);
        Komponen.addPlaceholderStyle(nameTextField);
        Komponen.addPlaceholderStyle(usernameTextField);
        Komponen.addPlaceholderStyle(emailTextField);
        Komponen.addPlaceholderStyle(phoneNumberTextField);
        Komponen.addPlaceholderStyle(passwordTextField);
        Komponen.addPlaceholderStyle(confirmationPasswordTextField);
        Komponen.setOnlyInteger(phoneNumberTextField);
        Komponen.setOnlyAlphaNumeric(nameTextField);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        leftRaedamLogo = new javax.swing.JLabel();
        leftTextRaedamLabel = new javax.swing.JLabel();
        rightRaedamLogo = new javax.swing.JLabel();
        carImageLabel = new javax.swing.JLabel();
        nameTextField = new java.awt.TextField();
        emailTextField = new java.awt.TextField();
        confirmationPasswordTextField = new java.awt.TextField();
        passwordTextField = new java.awt.TextField();
        registrationButton = new java.awt.Button();
        usernameTextField = new java.awt.TextField();
        phoneNumberTextField = new java.awt.TextField();
        haveAccountLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        eyeIcon1 = new javax.swing.JLabel();
        eyeIcon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        leftPanel.setBackground(new java.awt.Color(102, 204, 255));

        leftRaedamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/WhatsApp_Image_2023-10-17_at_12.55.56-removebg-preview.png"))); // NOI18N
        leftRaedamLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftRaedamLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftRaedamLogoMouseClicked(evt);
            }
        });

        leftTextRaedamLabel.setBackground(new java.awt.Color(255, 255, 255));
        leftTextRaedamLabel.setFont(new java.awt.Font("Al Bayan", 3, 24)); // NOI18N
        leftTextRaedamLabel.setForeground(new java.awt.Color(255, 255, 255));
        leftTextRaedamLabel.setText("Raedam.. Permudah Parkirmu!!!");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(leftRaedamLogo))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(leftTextRaedamLabel)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(leftRaedamLogo)
                .addGap(31, 31, 31)
                .addComponent(leftTextRaedamLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightRaedamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logo Kanan Atas.png"))); // NOI18N

        carImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/news 1.png"))); // NOI18N

        nameTextField.setBackground(new java.awt.Color(255, 255, 255));
        nameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTextField.setText("Nama Pengguna");
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });

        emailTextField.setBackground(new java.awt.Color(255, 255, 255));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.setText("Email");
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });

        confirmationPasswordTextField.setBackground(new java.awt.Color(255, 255, 255));
        confirmationPasswordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        confirmationPasswordTextField.setText("Konfirmasi Kata Sandi");
        confirmationPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmationPasswordTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmationPasswordTextFieldFocusLost(evt);
            }
        });

        passwordTextField.setBackground(new java.awt.Color(255, 255, 255));
        passwordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTextField.setText("Kata Sandi");
        passwordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextFieldFocusLost(evt);
            }
        });

        registrationButton.setBackground(new java.awt.Color(102, 204, 255));
        registrationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrationButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registrationButton.setForeground(new java.awt.Color(255, 255, 255));
        registrationButton.setLabel("Daftar");
        registrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButtonActionPerformed(evt);
            }
        });

        usernameTextField.setBackground(new java.awt.Color(255, 255, 255));
        usernameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameTextField.setText("Username");
        usernameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusLost(evt);
            }
        });

        phoneNumberTextField.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phoneNumberTextField.setText("Nomor Handphone");
        phoneNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNumberTextFieldFocusLost(evt);
            }
        });

        haveAccountLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        haveAccountLabel.setText("Sudah punya akun?");

        loginLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(51, 0, 255));
        loginLabel.setText("<html><u>Masuk</u></html>");
        loginLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
        });

        eyeIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/eye_pw2-removebg-preview (1).png"))); // NOI18N
        eyeIcon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyeIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeIcon1MouseClicked(evt);
            }
        });

        eyeIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/eye_pw2-removebg-preview (1).png"))); // NOI18N
        eyeIcon2.setText(" ");
        eyeIcon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyeIcon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeIcon2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rightRaedamLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(carImageLabel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmationPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(haveAccountLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eyeIcon1)
                            .addComponent(eyeIcon2))
                        .addGap(0, 182, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rightRaedamLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carImageLabel)
                .addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eyeIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eyeIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmationPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haveAccountLabel)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the registration button click and validates the registration input.
     */
    private void registrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButtonActionPerformed
        String namaPetugas = nameTextField.getText();
        String username = usernameTextField.getText();
        String emailPetugas = emailTextField.getText();
        String nomorHandphone = phoneNumberTextField.getText();
        String kataSandi = passwordTextField.getText();
        String konfirmasiKataSandi = confirmationPasswordTextField.getText();
        
        if (petugasC.validasiRegistrasi(username, namaPetugas, emailPetugas, nomorHandphone, kataSandi, konfirmasiKataSandi)){
            if (petugasC.isUsernameUnique(username)){
                if (petugasC.isLengthPasswordEnough(kataSandi)) {
                    if (petugasC.validateEmail(emailPetugas)){
                        petugasC.registrasiPetugas(namaPetugas, nomorHandphone, emailPetugas, username, kataSandi);
                        JOptionPane.showMessageDialog(Registrasi.this, "Anda berhasil registrasi");
                        new Login().setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Email Tidak Valid");
                    }
                } else {
                    JOptionPane.showMessageDialog(Registrasi.this, "Panjang password minimal 8 karakter!");
                }
            } else {
                JOptionPane.showMessageDialog(Registrasi.this, "Username sudah digunakan. Mohon gunakan username lain!");
            }
        } else {
            JOptionPane.showMessageDialog(Registrasi.this, "Masukkan semua data dengan benar!");
        }
    }//GEN-LAST:event_registrationButtonActionPerformed

    /**
     * Handles when focus is given to the name field, replacing the placeholder with an empty string.
     */
    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
        if(nameTextField.getText().equals("Nama Pengguna")){
            nameTextField.setText("");
            Komponen.removePlaceholderStyle(nameTextField);
        }
    }//GEN-LAST:event_nameTextFieldFocusGained

    /**
     * Handles when focus is given to the username field, replacing the placeholder with an empty string.
     */
    private void usernameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusGained
        if(usernameTextField.getText().equals("Username")){
            usernameTextField.setText("");
            Komponen.removePlaceholderStyle(usernameTextField);
        }
    }//GEN-LAST:event_usernameTextFieldFocusGained

    /**
     * Handles when focus is given to the email field, replacing the placeholder with an empty string.
     */
    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        if(emailTextField.getText().equals("Email")){
            emailTextField.setText("");
            Komponen.removePlaceholderStyle(emailTextField);
        }
    }//GEN-LAST:event_emailTextFieldFocusGained

    /**
     * Handles when focus is given to the phone number field, replacing the placeholder with an empty string.
     */
    private void phoneNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldFocusGained
        if(phoneNumberTextField.getText().equals("Nomor Handphone")){
            phoneNumberTextField.setText("");
            Komponen.removePlaceholderStyle(phoneNumberTextField);
        }
    }//GEN-LAST:event_phoneNumberTextFieldFocusGained

    /**
     * Handles when focus is given to the password field, replacing the placeholder with an empty string.
     */
    private void passwordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFieldFocusGained
       if(passwordTextField.getText().equals("Kata Sandi")){
            passwordTextField.setText("");
            passwordTextField.setEchoChar('*');
            Komponen.removePlaceholderStyle(passwordTextField);
        }
    }//GEN-LAST:event_passwordTextFieldFocusGained

    /**
     * Handles when focus is given to the confirmation password field, replacing the placeholder with an empty string.
     */
    private void confirmationPasswordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmationPasswordTextFieldFocusGained
        if(confirmationPasswordTextField.getText().equals("Konfirmasi Kata Sandi")){
            confirmationPasswordTextField.setText("");
            confirmationPasswordTextField.setEchoChar('*');
            Komponen.removePlaceholderStyle(confirmationPasswordTextField);
        }
    }//GEN-LAST:event_confirmationPasswordTextFieldFocusGained

    /**
     * Defines a method called when focus is lost from the name field, adding back the placeholder if no data is entered.
     */
    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
        if (nameTextField.getText().length()==0){
            Komponen.addPlaceholderStyle(nameTextField);
            nameTextField.setText("Nama Pengguna");
        } 
    }//GEN-LAST:event_nameTextFieldFocusLost

    /**
     * Defines a method called when focus is lost from the username field, adding back the placeholder if no data is entered.
     */
    private void usernameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusLost
        if (usernameTextField.getText().length()==0){
            Komponen.addPlaceholderStyle(usernameTextField);
            usernameTextField.setText("Username");
        } 
    }//GEN-LAST:event_usernameTextFieldFocusLost

    /**
     * Defines a method called when focus is lost from the email field, adding back the placeholder if no data is entered.
     */
    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        if (emailTextField.getText().length()==0){
            Komponen.addPlaceholderStyle(emailTextField);
            emailTextField.setText("Email");
        } 
    }//GEN-LAST:event_emailTextFieldFocusLost

    /**
     * Defines a method called when focus is lost from the phone number field, adding back the placeholder if no data is entered.
     */
    private void phoneNumberTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldFocusLost
        if (phoneNumberTextField.getText().length()==0){
            Komponen.addPlaceholderStyle(phoneNumberTextField);
            phoneNumberTextField.setText("Nomor Handphone");
        } 
    }//GEN-LAST:event_phoneNumberTextFieldFocusLost

    /**
     * Defines a method called when focus is lost from the password field, adding back the placeholder if no data is entered.
     */
    private void passwordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFieldFocusLost
        if (passwordTextField.getText().length()==0){
            Komponen.addPlaceholderStyle(passwordTextField);
            passwordTextField.setText("Kata Sandi");
        } 
    }//GEN-LAST:event_passwordTextFieldFocusLost

    /**
     * Defines a method called when focus is lost from the confirmation password field, adding back the placeholder if no data is entered.
     */
    private void confirmationPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmationPasswordTextFieldFocusLost
        if (confirmationPasswordTextField.getText().length()==0){
            Komponen.addPlaceholderStyle(confirmationPasswordTextField);
            confirmationPasswordTextField.setText("Konfirmasi Kata Sandi");
        } 
    }//GEN-LAST:event_confirmationPasswordTextFieldFocusLost

    /**
     * Ensures that the window remains focused.
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * Handles when the login label is clicked, opening the login form and closing the registration form.
     */
    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_loginLabelMouseClicked

    /**
     * Handles when the Raedam logo on the left is clicked, opening the welcome form and closing the registration form.
     */
    private void leftRaedamLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftRaedamLogoMouseClicked
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_leftRaedamLogoMouseClicked

    /**
     * Toggles the visibility of the password in a text field.
     */
    private void eyeIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeIcon1MouseClicked
        if (!showPassword){
            passwordTextField.setEchoChar((char) 0); 
            passwordTextField.setText(passwordTextField.getText());
            eyeIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/eye_pw-removebg-preview (1).png"))); 
        } else {
            passwordTextField.setEchoChar('*'); 
            passwordTextField.setText(passwordTextField.getText());
            eyeIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/eye_pw2-removebg-preview (1).png"))); 
        }
        showPassword = !showPassword;
    }//GEN-LAST:event_eyeIcon1MouseClicked

    /**
     * Toggles the visibility of the confirmation password in another text field.
     */
    private void eyeIcon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeIcon2MouseClicked
        if (!showConfirmationPassword){
            confirmationPasswordTextField.setEchoChar((char) 0); 
            confirmationPasswordTextField.setText(confirmationPasswordTextField.getText());
            eyeIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/eye_pw-removebg-preview (1).png"))); 
        } else {
            confirmationPasswordTextField.setEchoChar('*'); 
            confirmationPasswordTextField.setText(confirmationPasswordTextField.getText());
            eyeIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/eye_pw2-removebg-preview (1).png"))); 
        }
        showConfirmationPassword = !showConfirmationPassword;
    }//GEN-LAST:event_eyeIcon2MouseClicked

    /**
     * Main method to run the application.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carImageLabel;
    private java.awt.TextField confirmationPasswordTextField;
    private java.awt.TextField emailTextField;
    private javax.swing.JLabel eyeIcon1;
    private javax.swing.JLabel eyeIcon2;
    private javax.swing.JLabel haveAccountLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel leftRaedamLogo;
    private javax.swing.JLabel leftTextRaedamLabel;
    private javax.swing.JLabel loginLabel;
    private java.awt.TextField nameTextField;
    private java.awt.TextField passwordTextField;
    private java.awt.TextField phoneNumberTextField;
    private java.awt.Button registrationButton;
    private javax.swing.JLabel rightRaedamLogo;
    private java.awt.TextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
