package View;


import Controller.ParkirController;
import Controller.PembayaranController;
import Controller.PengaturanParkirController;
import java.util.Date;
import java.util.stream.Collectors;
import java.util.ArrayList;
import Model.Parkir;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pravi
 */

public class TampilData extends javax.swing.JFrame {
    
    /**
     * Creates new form TampilData
     */
    
    private final ParkirController parkirC = new ParkirController();
    private final PengaturanParkirController pengaturanC = new PengaturanParkirController();
    private final PembayaranController pembayaranC = new PembayaranController();
    
     
    public TampilData() {
        initComponents();   
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parkingSpaceAvailabilityInfoPanel = new javax.swing.JPanel();
        parkingSpaceAvilibilityLabel = new javax.swing.JLabel();
        motorcycleParkingAvailibilityValueLabel = new javax.swing.JLabel();
        motorcycleParkingAvailibilityLabel = new javax.swing.JLabel();
        carParkingAvailibilityLabel = new javax.swing.JLabel();
        carParkingAvailibilityValueLabel = new javax.swing.JLabel();
        laporanParkirTitleLabel = new javax.swing.JLabel();
        parkingAndPaymentInfoPanel = new javax.swing.JPanel();
        parkingAndPaymentTitleLabel = new javax.swing.JLabel();
        searchLabel = new java.awt.Button();
        datePicker = new com.toedter.calendar.JDateChooser();
        dateInputLabel = new javax.swing.JLabel();
        revenueTotalLabel = new javax.swing.JLabel();
        reveneuTotalValue = new javax.swing.JLabel();
        parkingAndPaymentInfoTableScrollPane = new javax.swing.JScrollPane();
        parkingAndPaymentInfoTable = new javax.swing.JTable();
        leftPanel = new javax.swing.JPanel();
        leftRaedamLogo = new javax.swing.JLabel();
        leftRaedamTextLabel = new javax.swing.JLabel();
        dashboardNavButton = new java.awt.Button();
        masukParkirNavButton = new java.awt.Button();
        keluarParkirNavButton = new java.awt.Button();
        pengaturanParkirNavButton = new java.awt.Button();
        laporanParkirNavButton = new java.awt.Button();
        raedamRightLogo = new javax.swing.JLabel();
        parkingDataInfoPanel = new javax.swing.JPanel();
        motorcycleInfoLabel = new javax.swing.JLabel();
        carInfoLabel = new javax.swing.JLabel();
        parkingTotalLabel = new javax.swing.JLabel();
        parkingDataInfoTitleLabel = new javax.swing.JLabel();
        parkingTotalValueLabel = new javax.swing.JLabel();
        carInfoValueLabel = new javax.swing.JLabel();
        motorcycleInfoValueLabel = new javax.swing.JLabel();
        dailyParkirInfoLabel = new javax.swing.JLabel();
        dailyParkirInfoValueLabel = new javax.swing.JLabel();
        hourlyParkingInfoLabel = new javax.swing.JLabel();
        hourlyParkingInfoValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parkingSpaceAvailabilityInfoPanel.setBackground(new java.awt.Color(102, 204, 255));

        parkingSpaceAvilibilityLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        parkingSpaceAvilibilityLabel.setForeground(new java.awt.Color(255, 255, 255));
        parkingSpaceAvilibilityLabel.setText("Total Ketersediaan Parkir: ");

        motorcycleParkingAvailibilityValueLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        motorcycleParkingAvailibilityValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        String kuotaMotor = "0";
        if (pengaturanC.getPengaturanParkir() != null) {
            kuotaMotor = String.valueOf(pengaturanC.getPengaturanParkir().getKuotaParkirMotor()-parkirC.getnMotor());
        }
        motorcycleParkingAvailibilityValueLabel.setText(kuotaMotor);

        motorcycleParkingAvailibilityLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        motorcycleParkingAvailibilityLabel.setForeground(new java.awt.Color(255, 255, 255));
        motorcycleParkingAvailibilityLabel.setText("Motor");

        carParkingAvailibilityLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        carParkingAvailibilityLabel.setForeground(new java.awt.Color(255, 255, 255));
        carParkingAvailibilityLabel.setText("Mobil");

        carParkingAvailibilityValueLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        carParkingAvailibilityValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        String kuotaMobil = "0";
        if (pengaturanC.getPengaturanParkir() != null) {
            kuotaMobil = String.valueOf(pengaturanC.getPengaturanParkir().getKuotaParkirMobil() - parkirC.getnMobil());
        }
        carParkingAvailibilityValueLabel.setText(kuotaMobil);

        javax.swing.GroupLayout parkingSpaceAvailabilityInfoPanelLayout = new javax.swing.GroupLayout(parkingSpaceAvailabilityInfoPanel);
        parkingSpaceAvailabilityInfoPanel.setLayout(parkingSpaceAvailabilityInfoPanelLayout);
        parkingSpaceAvailabilityInfoPanelLayout.setHorizontalGroup(
            parkingSpaceAvailabilityInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkingSpaceAvailabilityInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(parkingSpaceAvilibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(motorcycleParkingAvailibilityValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motorcycleParkingAvailibilityLabel)
                .addGap(172, 172, 172)
                .addComponent(carParkingAvailibilityValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carParkingAvailibilityLabel)
                .addGap(116, 116, 116))
        );
        parkingSpaceAvailabilityInfoPanelLayout.setVerticalGroup(
            parkingSpaceAvailabilityInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkingSpaceAvailabilityInfoPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(parkingSpaceAvailabilityInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parkingSpaceAvilibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motorcycleParkingAvailibilityValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motorcycleParkingAvailibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carParkingAvailibilityValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carParkingAvailibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(parkingSpaceAvailabilityInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 920, 70));

        laporanParkirTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        laporanParkirTitleLabel.setForeground(new java.awt.Color(102, 204, 255));
        laporanParkirTitleLabel.setText("LAPORAN PARKIR");
        getContentPane().add(laporanParkirTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 480, 90));

        parkingAndPaymentInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        parkingAndPaymentTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        parkingAndPaymentTitleLabel.setText("Data Parkir dan Pembayaran");

        searchLabel.setBackground(new java.awt.Color(102, 204, 255));
        searchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchLabel.setLabel("Cari");
        searchLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLabelActionPerformed(evt);
            }
        });

        dateInputLabel.setText("Masukkan Tanggal");

        revenueTotalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        revenueTotalLabel.setText("Total Pendapatan :");

        reveneuTotalValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reveneuTotalValue.setText(String.valueOf(pembayaranC.hitungTotalPendapatan(false, new Date())));

        parkingAndPaymentInfoTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        parkingAndPaymentInfoTable.setFont(new java.awt.Font("Tahoma", 0, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tipe Parkir");
        model.addColumn("Plat Nomor");
        model.addColumn("Jenis Kendaraan");
        model.addColumn("Waktu Masuk");
        model.addColumn("Waktu Keluar");
        model.addColumn("Status Parkir");

        JTable table1 = new JTable(model);
        parkingAndPaymentInfoTableScrollPane.setViewportView(parkingAndPaymentInfoTable);

        javax.swing.GroupLayout parkingAndPaymentInfoPanelLayout = new javax.swing.GroupLayout(parkingAndPaymentInfoPanel);
        parkingAndPaymentInfoPanel.setLayout(parkingAndPaymentInfoPanelLayout);
        parkingAndPaymentInfoPanelLayout.setHorizontalGroup(
            parkingAndPaymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkingAndPaymentInfoPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(parkingAndPaymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parkingAndPaymentInfoPanelLayout.createSequentialGroup()
                        .addComponent(dateInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(revenueTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reveneuTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(parkingAndPaymentTitleLabel)
                    .addGroup(parkingAndPaymentInfoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(parkingAndPaymentInfoTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        parkingAndPaymentInfoPanelLayout.setVerticalGroup(
            parkingAndPaymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parkingAndPaymentInfoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(parkingAndPaymentTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(parkingAndPaymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(parkingAndPaymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(dateInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(parkingAndPaymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(revenueTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reveneuTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(parkingAndPaymentInfoTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(parkingAndPaymentInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 920, 500));

        leftPanel.setBackground(new java.awt.Color(102, 204, 255));

        leftRaedamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/WhatsApp_Image_2023-10-17_at_12.55.56-removebg-preview.png"))); // NOI18N
        leftRaedamLogo.setText("jLabel4");

        leftRaedamTextLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        leftRaedamTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        leftRaedamTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftRaedamTextLabel.setText("Raedam");

        dashboardNavButton.setActionCommand("beranda");
        dashboardNavButton.setBackground(new java.awt.Color(102, 204, 255));
        dashboardNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        dashboardNavButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardNavButton.setLabel("Beranda");
        dashboardNavButton.setPreferredSize(new java.awt.Dimension(116, 41));
        dashboardNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardNavButtonActionPerformed(evt);
            }
        });

        masukParkirNavButton.setActionCommand("masukParkir");
        masukParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        masukParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masukParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        masukParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        masukParkirNavButton.setLabel("Masuk Parkir");
        masukParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukParkirNavButtonActionPerformed(evt);
            }
        });

        keluarParkirNavButton.setActionCommand("keluarParkir");
        keluarParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        keluarParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluarParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        keluarParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        keluarParkirNavButton.setLabel("Keluar Parkir");
        keluarParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarParkirNavButtonActionPerformed(evt);
            }
        });

        pengaturanParkirNavButton.setActionCommand("pengaturanParkir");
        pengaturanParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        pengaturanParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengaturanParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        pengaturanParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        pengaturanParkirNavButton.setLabel("Pengaturan Parkir");
        pengaturanParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengaturanParkirNavButtonActionPerformed(evt);
            }
        });

        laporanParkirNavButton.setActionCommand("laporanParkir");
        laporanParkirNavButton.setBackground(new java.awt.Color(102, 204, 255));
        laporanParkirNavButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanParkirNavButton.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        laporanParkirNavButton.setForeground(new java.awt.Color(255, 255, 255));
        laporanParkirNavButton.setLabel("Laporan Parkir");
        laporanParkirNavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanParkirNavButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(leftRaedamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(leftRaedamTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(masukParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keluarParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pengaturanParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laporanParkirNavButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(leftRaedamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leftRaedamTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(dashboardNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(masukParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(keluarParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pengaturanParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(laporanParkirNavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(846, Short.MAX_VALUE))
        );

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        raedamRightLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logo Kanan Atas.png"))); // NOI18N
        getContentPane().add(raedamRightLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, -1, -1));

        parkingDataInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        motorcycleInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        motorcycleInfoLabel.setText("Motor : ");

        carInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        carInfoLabel.setText("Mobil : ");

        parkingTotalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        parkingTotalLabel.setText("Total Terisi :");

        parkingDataInfoTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        parkingDataInfoTitleLabel.setText("Data Parkir");

        parkingTotalValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        parkingTotalValueLabel.setText(String.valueOf(parkirC.getnMotor()+parkirC.getnMobil()));

        carInfoValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        carInfoValueLabel.setText(String.valueOf(parkirC.getnMobil()));

        motorcycleInfoValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        String motor = "0";
        motorcycleInfoValueLabel.setText(String.valueOf(parkirC.getnMotor()));

        dailyParkirInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dailyParkirInfoLabel.setText("Parkir Inap :");

        dailyParkirInfoValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dailyParkirInfoValueLabel.setText(String.valueOf(parkirC.getListParkirParkir().stream().filter(e -> e.getTipeParkir().equalsIgnoreCase("INAP")).collect(Collectors.toList()).size()));

        hourlyParkingInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hourlyParkingInfoLabel.setText("Parkir PerJam :");

        hourlyParkingInfoValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hourlyParkingInfoValueLabel.setText(String.valueOf(parkirC.getListParkirParkir().stream().filter(e -> e.getTipeParkir().equalsIgnoreCase("PERJAM")).collect(Collectors.toList()).size()));

        javax.swing.GroupLayout parkingDataInfoPanelLayout = new javax.swing.GroupLayout(parkingDataInfoPanel);
        parkingDataInfoPanel.setLayout(parkingDataInfoPanelLayout);
        parkingDataInfoPanelLayout.setHorizontalGroup(
            parkingDataInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkingDataInfoPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(parkingDataInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parkingDataInfoPanelLayout.createSequentialGroup()
                        .addComponent(parkingDataInfoTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(parkingDataInfoPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(motorcycleInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(motorcycleInfoValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(carInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carInfoValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(dailyParkirInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dailyParkirInfoValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(hourlyParkingInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hourlyParkingInfoValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(parkingTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parkingTotalValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        parkingDataInfoPanelLayout.setVerticalGroup(
            parkingDataInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkingDataInfoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(parkingDataInfoTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parkingDataInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motorcycleInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motorcycleInfoValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carInfoValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailyParkirInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailyParkirInfoValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourlyParkingInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourlyParkingInfoValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkingTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkingTotalValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(parkingDataInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 920, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action when the "Beranda" button is clicked.
     */
    private void dashboardNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardNavButtonActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_dashboardNavButtonActionPerformed

    /**
     * Handles the action when the "Masuk Parkir" button is clicked.
     */
    private void masukParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new MasukParkir().setVisible(true);
        dispose();
    }//GEN-LAST:event_masukParkirNavButtonActionPerformed

    /**
     * Handles the action when the "Keluar Parkir" button is clicked.
     */
    private void keluarParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new KeluarParkir().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarParkirNavButtonActionPerformed

    /**
     * Handles the action when the "Pengaturan Parkir" button is clicked.
     */
    private void pengaturanParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengaturanParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new PengaturanParkirView().setVisible(true);
        dispose();
    }//GEN-LAST:event_pengaturanParkirNavButtonActionPerformed

    /**
     * Handles the action when the "Laporan Parkir" button is clicked.
     */
    private void laporanParkirNavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanParkirNavButtonActionPerformed
        // TODO add your handling code here:
        new TampilData().setVisible(true);
        dispose();
    }//GEN-LAST:event_laporanParkirNavButtonActionPerformed

    
    /**
     * The searchLabelActionPerformed method is triggered when the user interacts with the search label, typically to search for parking data based on a selected date. 
     * @param evt 
     */
    private void searchLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLabelActionPerformed
        Date tanggal = datePicker.getDate();
        ArrayList<Parkir> parkirTerpilih = parkirC.searchParkirByTanggal(tanggal);
        
        if (tanggal != null && parkirTerpilih.size() > 0){ 
            DefaultTableModel model = Komponen.CreateTableModelParkir(parkirTerpilih);
            parkingAndPaymentInfoTable.setModel(model);
            reveneuTotalValue.setText(String.valueOf(pembayaranC.hitungTotalPendapatan(true, tanggal)));            
        } else if (tanggal != null && parkirTerpilih.isEmpty()){
            JOptionPane.showMessageDialog(TampilData.this, "Data Parkir Tidak Ditemukan");
        }else {
            JOptionPane.showMessageDialog(TampilData.this, "Masukkan tanggal parkir yang akan dicari");
        }
    }//GEN-LAST:event_searchLabelActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carInfoLabel;
    private javax.swing.JLabel carInfoValueLabel;
    private javax.swing.JLabel carParkingAvailibilityLabel;
    private javax.swing.JLabel carParkingAvailibilityValueLabel;
    private javax.swing.JLabel dailyParkirInfoLabel;
    private javax.swing.JLabel dailyParkirInfoValueLabel;
    private java.awt.Button dashboardNavButton;
    private javax.swing.JLabel dateInputLabel;
    private com.toedter.calendar.JDateChooser datePicker;
    private javax.swing.JLabel hourlyParkingInfoLabel;
    private javax.swing.JLabel hourlyParkingInfoValueLabel;
    private java.awt.Button keluarParkirNavButton;
    private java.awt.Button laporanParkirNavButton;
    private javax.swing.JLabel laporanParkirTitleLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel leftRaedamLogo;
    private javax.swing.JLabel leftRaedamTextLabel;
    private java.awt.Button masukParkirNavButton;
    private javax.swing.JLabel motorcycleInfoLabel;
    private javax.swing.JLabel motorcycleInfoValueLabel;
    private javax.swing.JLabel motorcycleParkingAvailibilityLabel;
    private javax.swing.JLabel motorcycleParkingAvailibilityValueLabel;
    private javax.swing.JPanel parkingAndPaymentInfoPanel;
    private javax.swing.JTable parkingAndPaymentInfoTable;
    private javax.swing.JScrollPane parkingAndPaymentInfoTableScrollPane;
    private javax.swing.JLabel parkingAndPaymentTitleLabel;
    private javax.swing.JPanel parkingDataInfoPanel;
    private javax.swing.JLabel parkingDataInfoTitleLabel;
    private javax.swing.JPanel parkingSpaceAvailabilityInfoPanel;
    private javax.swing.JLabel parkingSpaceAvilibilityLabel;
    private javax.swing.JLabel parkingTotalLabel;
    private javax.swing.JLabel parkingTotalValueLabel;
    private java.awt.Button pengaturanParkirNavButton;
    private javax.swing.JLabel raedamRightLogo;
    private javax.swing.JLabel reveneuTotalValue;
    private javax.swing.JLabel revenueTotalLabel;
    private java.awt.Button searchLabel;
    // End of variables declaration//GEN-END:variables

}


